### ISSUE TITLE
OpenvisionAPI Server is running?

### ISSUE THREAD

**Issue by ricardolimaui** [openvisionapi/ova-client#1]
Hello, 

Thank you by this API. 
Currently the api is not working isn't it? It was working normally, but now it is giving the following error
`HTTPSConnectionPool(host='api.openvisionapi.com', port=443): Max retries exceeded with url: /api/v1/detection (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10bf95310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))`

Anyone can help me to solve this?

Thank you

**Comment by pythops** [comment]
I've stopped the server for the moment. I need some sort of sponsoring to able to pay the the running instance.
