### ISSUE TITLE
API not available

### ISSUE THREAD

**Issue by sudoariel** [openvisionapi/ova-client#2]
Hi,
I am trying to use this API but I am not able to connect to the endpoint.
I followed the documentation and tested it using the following curl command:
`curl -X POST https://api.openvisionapi.com/api/v1/detection   -F "model=yolov4"   -F "image=@images/cat.jpeg"`
And then I am getting it:
`curl: (6) Could not resolve host: api.openvisionapi.com`

![image](https://user-images.githubusercontent.com/35286078/145252598-8513f966-ffb8-4aa4-b2a7-d7284aa9eebb.png)

Some weeks ago I was able to use this API normally. Is it still available?

**Comment by pythops** [comment]
I had to shut it down unfortunately.
I'm gonna setup soon sponsoring program so I can have funds to be able to pay for the public instance.
